Repository entando/entando-engine, pull requests merged in 2020-09, with the labels that each got.

#32 ENG-1144 Filling profileType data
  src/main/java/org/entando/entando/aps/system/services/user/model/ProfileTypeDto.java
  src/main/java/org/entando/entando/aps/system/services/user/model/UserDto.java
  src/test/java/org/entando/entando/web/user/UserControllerIntegrationTest.java
Labels: approved, size/M

#33 ENG-1158 ENG-1156 ootb users with roles and permissions added
  src/main/resources/sql/entandoServ_data_production.sql
Labels: approved, size/S

#31 ENG-408 updated widget usage count
  src/main/java/org/entando/entando/aps/system/services/widgettype/model/WidgetDtoBuilder.java
  src/test/java/org/entando/entando/aps/system/services/widgettype/WidgetServiceTest.java
  src/test/java/org/entando/entando/web/widget/WidgetControllerIntegrationTest.java
Labels: size/S

#36 ENG-1130 update user profile attributes
  src/main/java/org/entando/entando/aps/system/services/entity/AbstractEntityService.java
  src/main/java/org/entando/entando/aps/system/services/entity/model/EntityAttributeDto.java
  src/main/java/org/entando/entando/aps/system/services/entity/model/EntityDto.java
  src/test/java/org/entando/entando/web/userprofile/6_POST_type_valid.json
  src/test/java/org/entando/entando/web/userprofile/6_PUT_valid.json
  src/test/java/org/entando/entando/web/userprofile/7_PUT_valid.json
  src/test/java/org/entando/entando/web/userprofile/UserProfileControllerIntegrationTest.java
Labels: approved, size/L

#40 ENG-1201 Adding a new field in attributes called names to hold differ…
  src/main/java/com/agiletec/aps/system/common/entity/model/attribute/AbstractAttribute.java
  src/main/java/com/agiletec/aps/system/common/entity/model/attribute/AbstractJAXBAttribute.java
  src/main/java/com/agiletec/aps/system/common/entity/model/attribute/AttributeInterface.java
  src/main/java/com/agiletec/aps/system/common/entity/model/attribute/DefaultJAXBAttributeType.java
  src/main/java/org/entando/entando/aps/system/services/entity/AbstractEntityTypeService.java
  src/main/java/org/entando/entando/aps/system/services/entity/model/EntityTypeAttributeDto.java
Labels: size/L

#35 ENG-1075: Fix entando-engine critical vulnerabilities ENG-1232, ENG-1250, ENG-1233, ENG-1236
  src/main/java/com/agiletec/aps/system/services/page/PageDAO.java
  src/main/java/org/entando/entando/aps/system/services/api/provider/jsonp/JSONPProvider.java
  src/main/java/org/entando/entando/aps/system/services/database/DatabaseService.java
  src/main/java/org/entando/entando/aps/system/services/storage/FileBrowserService.java
  src/main/java/org/entando/entando/ent/exception/ApsException.java
  src/main/java/org/entando/entando/ent/exception/ApsSystemException.java
  src/main/java/org/entando/entando/web/database/DatabaseController.java
  src/main/java/org/entando/entando/web/filebrowser/FileBrowserController.java
  src/main/resources/spring/aps/restServerObjects.xml
Labels: do-not-merge/work-in-progress, size/L

#45 ENG-1075: Remove jsonpProvider refences
  src/main/resources/spring/restServerConfig.xml
Labels: size/XS

#41 ENG-1277: Introduce fist version of logger sanitization wrapper
  src/main/java/com/agiletec/aps/util/ForJLogger.java
  src/main/java/org/entando/entando/ent/util/EntLogging.java
  src/test/java/com/agiletec/aps/AllTests.java
  src/test/java/org/entando/entando/ent/util/EntLoggingTest.java
Labels: size/XXL

#44 ENG-1280 Adding fallback to name
  src/main/java/com/agiletec/aps/system/common/entity/model/attribute/AbstractAttribute.java
  src/main/java/org/entando/entando/aps/system/services/entity/AbstractEntityTypeService.java
Labels: size/M

#47 ENG-1283 create categories usage count endpoint
  src/main/java/org/entando/entando/aps/system/services/category/CategoryService.java
  src/main/java/org/entando/entando/aps/system/services/category/ICategoryService.java
  src/main/java/org/entando/entando/web/category/CategoryController.java
  src/test/java/org/entando/entando/web/category/CategoryControllerIntegrationTest.java
Labels: size/M

#46 Eng 1278 add usage count endpoint for groups
  src/main/java/org/entando/entando/aps/system/services/group/GroupService.java
  src/main/java/org/entando/entando/aps/system/services/group/IGroupService.java
  src/main/java/org/entando/entando/web/group/GroupController.java
  src/test/java/org/entando/entando/web/group/GroupControllerIntegrationTest.java
Labels: approved, size/L

#48 Eng 703 as an entando developer i would like the swagger ui enabled by default so i can more easily see and test the available apis
  src/main/java/com/agiletec/aps/system/SystemConstants.java
  src/main/java/org/entando/entando/web/swagger/SwaggerConfig.java
  src/main/resources/spring/aps/restServerObjects.xml
  src/test/java/com/agiletec/aps/AllTests.java
  src/test/java/org/entando/entando/web/swagger/SwaggerConfigTest.java
  src/test/java/org/entando/entando/web/swagger/SwaggerMvcAdapterTest.java
Labels: approved, size/L

#49 'ENG-1232: Revert ApsSystemUtils.getLogger for backward compatibility
  src/main/java/com/agiletec/aps/system/ApsSystemUtils.java
Labels: size/XS

#37 ENG-1075: Fix entando-engine critical vulnerabilities ENG-1233 (XXE), ENG-1234 (XSS), ENG-1235 (WeakEncr), ENG-1296 (PubStatMutable)
  src/main/java/com/agiletec/aps/system/SystemConstants.java
  src/main/java/com/agiletec/aps/system/common/entity/ApsEntityManager.java
  src/main/java/com/agiletec/aps/system/common/entity/parse/AbstractAttributeSupportObjectDOM.java
  src/main/java/com/agiletec/aps/system/exception/EntRuntimeException.java
  src/main/java/com/agiletec/aps/system/services/baseconfig/BaseConfigManager.java
  src/main/java/com/agiletec/aps/system/services/baseconfig/ConfigInterface.java
  src/main/java/com/agiletec/aps/system/services/user/UserManager.java
  src/main/java/com/agiletec/aps/util/FileTextReader.java
  src/main/java/org/entando/entando/aps/system/init/DatabaseManager.java
  src/main/java/org/entando/entando/aps/system/init/util/ComponentDefDOM.java
  src/main/java/org/entando/entando/aps/system/services/api/ApiResourcesDefDOM.java
  src/main/java/org/entando/entando/aps/system/services/api/ApiServiceInterface.java
  src/main/java/org/entando/entando/aps/system/services/api/server/ApiRestServer.java
  src/main/java/org/entando/entando/aps/system/services/oauth2/IOAuthConsumerManager.java
  src/main/java/org/entando/entando/aps/system/services/page/PageTokenManager.java
  src/main/java/org/entando/entando/aps/system/services/storage/LocalStorageManager.java
  src/main/java/org/entando/entando/aps/util/crypto/CompatiblePasswordEncoder.java
  src/main/java/org/entando/entando/aps/util/crypto/LegacyPasswordEncryptor.java
  src/main/java/org/entando/entando/ent/util/EntSafeXmlUtils.java
  src/main/java/org/entando/entando/web/api/oauth2/validator/ApiConsumerValidator.java
  src/main/resources/sql/entandoServ_data_production.sql
  src/test/java/com/agiletec/aps/system/services/user/UserManagerTest.java
  src/test/java/org/entando/entando/aps/util/crypto/CompatiblePasswordEncoderTest.java
  src/test/java/org/entando/entando/ent/util/EntSafeXmlUtilsTest.java
  src/test/resources/sql/entandoServ_data_test.sql
Labels: approved, do-not-merge/work-in-progress, size/L

#50 ENG-1248 widget locked field added to APIs responses
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetService.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/model/WidgetDto.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/model/WidgetDtoBuilder.java
  src/main/java/org/entando/entando/web/widget/WidgetController.java
  src/main/java/org/entando/entando/web/widget/validator/WidgetValidator.java
  src/main/resources/rest/messages.properties
  src/test/java/org/entando/entando/web/widget/WidgetControllerTest.java
Labels: approved, size/L

#52 ENG-1267 Creating user with profile
  src/main/java/org/entando/entando/aps/system/services/user/UserService.java
  src/main/java/org/entando/entando/web/user/model/UserRequest.java
  src/main/java/org/entando/entando/web/user/validator/UserValidator.java
  src/test/java/org/entando/entando/web/user/1_POST_profile_type.json
  src/test/java/org/entando/entando/web/user/1_POST_user_with_default_profile.json
  src/test/java/org/entando/entando/web/user/1_POST_user_with_profile.json
  src/test/java/org/entando/entando/web/user/UserControllerIntegrationTest.java
Labels: approved, size/L

#54 ENG-1298 Adding names to propOrder
  src/main/java/com/agiletec/aps/system/common/entity/model/attribute/DefaultJAXBAttributeType.java
Labels: approved, size/XS

#51 Eng 1289 groups labels categories submission idempotent
  src/main/java/org/entando/entando/aps/system/services/category/CategoryService.java
  src/main/java/org/entando/entando/aps/system/services/category/model/CategoryDto.java
  src/main/java/org/entando/entando/aps/system/services/group/GroupService.java
  src/main/java/org/entando/entando/aps/system/services/label/LabelService.java
  src/main/java/org/entando/entando/web/category/validator/CategoryValidator.java
  src/main/java/org/entando/entando/web/common/RestErrorCodes.java
  src/main/java/org/entando/entando/web/common/handlers/RestExceptionHandler.java
  src/main/java/org/entando/entando/web/group/GroupController.java
  src/main/java/org/entando/entando/web/group/validator/GroupValidator.java
  src/main/resources/rest/messages.properties
  src/main/resources/spring/aps/servicesConfig.xml
  src/main/resources/spring/aps/validators.xml
  src/test/java/org/entando/entando/aps/system/services/category/CategoryServiceTest.java
  src/test/java/org/entando/entando/aps/system/services/category/CategoryTestHelper.java
  src/test/java/org/entando/entando/aps/system/services/group/GroupServiceTest.java
  src/test/java/org/entando/entando/aps/system/services/group/GroupTestHelper.java
  src/test/java/org/entando/entando/aps/system/services/label/LabelServiceTest.java
  src/test/java/org/entando/entando/aps/system/services/label/LabelTestHelper.java
  src/test/java/org/entando/entando/web/category/CategoryControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/group/GroupControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/label/LabelControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/label/LabelControllerUnitTest.java
Labels: size/XXL

#55 ENG-1303 Adding some tests to prove that is possible to update inacti…
  src/test/java/org/entando/entando/web/user/1_PUT_user_with_profile.json
  src/test/java/org/entando/entando/web/user/UserControllerIntegrationTest.java
Labels: size/M

#58 ENG-1295 Saving regex for entity types
  src/main/java/org/entando/entando/aps/system/services/entity/model/EntityTypeAttributeValidationDto.java
  src/test/java/org/entando/entando/web/userprofile/8_POST_regex.json
  src/test/java/org/entando/entando/web/userprofile/8_PUT_regex.json
  src/test/java/org/entando/entando/web/userprofile/ProfileTypeControllerIntegrationTest.java
Labels: approved, size/L
