Repository entando/entando-engine, pull requests merged in 2020-10, with the labels that each got.

#59 ENG-1248 Widget type validation refactoring and tests added
  src/main/java/org/entando/entando/web/widget/validator/WidgetValidator.java
  src/test/java/org/entando/entando/web/widget/WidgetControllerIntegrationTest.java
Labels: size/M

#60 ENG-1005: Set required permission for Legacy API getUserProfile and getUserProfiles
  src/main/resources/api/aps/apiMethods.xml
  src/test/java/org/entando/entando/aps/system/services/api/ApiCatalogManagerTest.java
Labels: approved, lgtm, size/XL

#62 ENG-1338: Add explicit IV to better support specific java8 versions
  src/main/java/org/entando/entando/aps/system/services/page/PageTokenManager.java
  src/test/java/com/agiletec/aps/AllTests.java
  src/test/java/org/entando/entando/aps/system/services/page/PageTokenManagerTest.java
Labels: size/M

#63 ENG-1348: update pom xml for spring security oauth vulnerability
  pom.xml
Labels: size/XS

#56 ENG-1244 new readonlyDefaultConfig field added in widget type
  src/main/db/update/scriptPort.sql
  src/main/java/org/entando/entando/aps/system/init/model/portdb/WidgetCatalog.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/IWidgetTypeDAO.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/IWidgetTypeManager.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetService.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetType.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetTypeDAO.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetTypeManager.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/api/ApiWidgetTypeInterface.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/api/JAXBWidgetType.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/model/WidgetDto.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/model/WidgetDtoBuilder.java
  src/main/java/org/entando/entando/web/page/PageConfigurationController.java
  src/main/java/org/entando/entando/web/page/validator/PageConfigurationValidator.java
  src/main/java/org/entando/entando/web/widget/model/WidgetRequest.java
  src/main/resources/rest/messages.properties
  src/main/resources/sql/entandoPort_data_production.sql
  src/test/java/com/agiletec/aps/ControllersAllTests.java
  src/test/java/com/agiletec/aps/system/services/widgettype/TestWidgetTypeManager.java
  src/test/java/org/entando/entando/aps/system/services/widgettype/WidgetServiceTest.java
  src/test/java/org/entando/entando/aps/system/services/widgettype/api/TestApiWidgetTypeInterface.java
  src/test/java/org/entando/entando/web/page/PageConfigurationControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/widget/WidgetControllerIntegrationTest.java
  src/test/resources/sql/entandoPort_data_test.sql
Labels: approved, size/XXL

#57 ENG-1206: Introduced EMAIL attribute type
  src/main/java/com/agiletec/aps/system/common/entity/model/attribute/DefaultJAXBAttributeType.java
  src/main/java/org/entando/entando/aps/system/common/entity/model/attribute/EmailAttribute.java
  src/main/java/org/entando/entando/aps/system/services/userprofile/attributeRoles.xml
  src/main/resources/spring/aps/managers/attributeTypesDef.xml
  src/main/resources/spring/aps/managers/entityManagerDef.xml
  src/test/java/com/agiletec/aps/AllTests.java
  src/test/java/org/entando/entando/aps/system/services/entity/EntityManagerServiceIntegrationTest.java
  src/test/java/org/entando/entando/aps/system/services/userprofile/ValidateUserProfileIntegrationTest.java
  src/test/java/org/entando/entando/web/dataobject/DataTypeControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/user/UserControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/userprofile/ProfileTypeControllerIntegrationTest.java
  src/test/resources/sql/entandoPort_data_test.sql
Labels: approved, lgtm, size/XL

#64 ENG-1332 Adding column wizard enabled to User
  src/main/db/update/scriptServ.sql
  src/main/java/com/agiletec/aps/system/services/user/IUserDAO.java
  src/main/java/com/agiletec/aps/system/services/user/IUserManager.java
  src/main/java/com/agiletec/aps/system/services/user/User.java
  src/main/java/com/agiletec/aps/system/services/user/UserDAO.java
  src/main/java/com/agiletec/aps/system/services/user/UserDetails.java
  src/main/java/com/agiletec/aps/system/services/user/UserManager.java
  src/main/java/org/entando/entando/aps/system/init/model/servdb/User.java
  src/main/java/org/entando/entando/aps/system/services/user/IUserService.java
  src/main/java/org/entando/entando/aps/system/services/user/UserService.java
  src/main/java/org/entando/entando/aps/system/services/user/model/UserDto.java
  src/main/java/org/entando/entando/web/user/UserController.java
  src/main/java/org/entando/entando/web/user/model/UserRequest.java
  src/main/java/org/entando/entando/web/user/model/UserWizardRequest.java
  src/main/java/org/entando/entando/web/user/validator/UserValidator.java
  src/main/resources/rest/messages.properties
  src/main/resources/sql/entandoServ_data_production.sql
  src/test/java/org/entando/entando/web/user/1_POST_user_with_default_profile.json
  src/test/java/org/entando/entando/web/user/1_POST_user_wizard_disabled.json
  src/test/java/org/entando/entando/web/user/1_POST_user_wizard_enabled.json
  src/test/java/org/entando/entando/web/user/1_PUT_user_with_profile.json
  src/test/java/org/entando/entando/web/user/UserControllerIntegrationTest.java
  src/test/resources/sql/entandoServ_data_test.sql
Labels: approved, lgtm, size/L

#65 ENG-1244 readonlyDefaultConfig cache update
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetTypeManager.java
  src/test/java/com/agiletec/aps/system/services/widgettype/TestWidgetTypeManager.java
Labels: approved, size/S

#66 ENG-1349 widget renaming
  src/main/resources/sql/entandoPort_data_production.sql
Labels: size/S

#39 ENG-531: Core upgrade for redis integration
  src/main/java/com/agiletec/aps/system/common/AbstractCacheWrapper.java
  src/main/java/org/entando/entando/aps/system/services/cache/CacheInfoManager.java
  src/main/resources/spring/aps/managers/apiManagersConfig.xml
  src/main/resources/spring/aps/managers/baseManagersConfig.xml
  src/main/resources/spring/aps/managers/dataManagersConfig.xml
  src/main/resources/spring/aps/managers/entityManagerDef.xml
  src/main/resources/spring/baseSystemConfig.xml
Labels: size/L

#61 ENG-1180: Improve cache support for clustered environments
  src/main/java/com/agiletec/aps/system/common/AbstractCacheWrapper.java
  src/main/java/com/agiletec/aps/system/common/AbstractGenericCacheWrapper.java
  src/main/java/com/agiletec/aps/system/common/ICacheWrapper.java
  src/main/java/com/agiletec/aps/system/common/entity/cache/EntityManagerCacheWrapper.java
  src/main/java/com/agiletec/aps/system/services/baseconfig/BaseConfigManager.java
  src/main/java/com/agiletec/aps/system/services/baseconfig/cache/ConfigManagerCacheWrapper.java
  src/main/java/com/agiletec/aps/system/services/baseconfig/cache/IConfigManagerCacheWrapper.java
  src/main/java/com/agiletec/aps/system/services/category/CategoryManager.java
  src/main/java/com/agiletec/aps/system/services/category/cache/CategoryManagerCacheWrapper.java
  src/main/java/com/agiletec/aps/system/services/category/cache/ICategoryManagerCacheWrapper.java
  src/main/java/com/agiletec/aps/system/services/group/GroupManager.java
  src/main/java/com/agiletec/aps/system/services/group/cache/GroupManagerCacheWrapper.java
  src/main/java/com/agiletec/aps/system/services/group/cache/IGroupManagerCacheWrapper.java
  src/main/java/com/agiletec/aps/system/services/i18n/I18nManager.java
  src/main/java/com/agiletec/aps/system/services/i18n/cache/I18nManagerCacheWrapper.java
  src/main/java/com/agiletec/aps/system/services/i18n/cache/II18nManagerCacheWrapper.java
  src/main/java/com/agiletec/aps/system/services/keygenerator/KeyGeneratorManager.java
  src/main/java/com/agiletec/aps/system/services/keygenerator/cache/IKeyGeneratorManagerCacheWrapper.java
  src/main/java/com/agiletec/aps/system/services/keygenerator/cache/KeyGeneratorManagerCacheWrapper.java
  src/main/java/com/agiletec/aps/system/services/page/PageManager.java
  src/main/java/com/agiletec/aps/system/services/page/cache/IPageManagerCacheWrapper.java
  src/main/java/com/agiletec/aps/system/services/page/cache/PageManagerCacheWrapper.java
  src/main/java/com/agiletec/aps/system/services/pagemodel/PageModelManager.java
  src/main/java/com/agiletec/aps/system/services/pagemodel/cache/IPageModelManagerCacheWrapper.java
  src/main/java/com/agiletec/aps/system/services/pagemodel/cache/PageModelManagerCacheWrapper.java
  src/main/java/com/agiletec/aps/system/services/role/RoleManager.java
  src/main/java/com/agiletec/aps/system/services/role/cache/IPermissionCacheWrapper.java
  src/main/java/com/agiletec/aps/system/services/role/cache/IRoleCacheWrapper.java
  src/main/java/com/agiletec/aps/system/services/role/cache/PermissionCacheWrapper.java
  src/main/java/com/agiletec/aps/system/services/role/cache/RoleCacheWrapper.java
  src/main/java/org/entando/entando/aps/system/init/cache/IInitializerManagerCacheWrapper.java
  src/main/java/org/entando/entando/aps/system/init/cache/InitializerManagerCacheWrapper.java
  src/main/java/org/entando/entando/aps/system/services/api/ApiCatalogManager.java
  src/main/java/org/entando/entando/aps/system/services/api/cache/ApiResourceCacheWrapper.java
  src/main/java/org/entando/entando/aps/system/services/api/cache/ApiServiceCacheWrapper.java
  src/main/java/org/entando/entando/aps/system/services/api/cache/IApiResourceCacheWrapper.java
  src/main/java/org/entando/entando/aps/system/services/api/cache/IApiServiceCacheWrapper.java
  src/main/java/org/entando/entando/aps/system/services/dataobjectmapper/DataObjectPageMapperManager.java
  src/main/java/org/entando/entando/aps/system/services/dataobjectmapper/cache/DataObjectMapperCacheWrapper.java
  src/main/java/org/entando/entando/aps/system/services/dataobjectmapper/cache/IDataObjectMapperCacheWrapper.java
  src/main/java/org/entando/entando/aps/system/services/dataobjectmodel/DataObjectModelManager.java
  src/main/java/org/entando/entando/aps/system/services/dataobjectmodel/cache/DataObjectModelCacheWrapper.java
  src/main/java/org/entando/entando/aps/system/services/dataobjectmodel/cache/IDataObjectModelCacheWrapper.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetTypeManager.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/cache/IWidgetTypeManagerCacheWrapper.java
Labels: size/L

#68 Change email attribute type from "Monotext" to Email"...
  src/main/resources/sql/entandoPort_data_production.sql
Labels: approved, size/XS

#70 ENG-1377 cosmetic feedback - renaming service page to single frame page
  src/main/resources/sql/entandoPort_data_production.sql
Labels: size/S

#69 ENG-1383 adding user preferences api
  src/main/db/update/scriptPort.sql
  src/main/db/update/scriptServ.sql
  src/main/java/com/agiletec/aps/system/services/user/IUserDAO.java
  src/main/java/com/agiletec/aps/system/services/user/IUserManager.java
  src/main/java/com/agiletec/aps/system/services/user/User.java
  src/main/java/com/agiletec/aps/system/services/user/UserDAO.java
  src/main/java/com/agiletec/aps/system/services/user/UserDetails.java
  src/main/java/com/agiletec/aps/system/services/user/UserManager.java
  src/main/java/org/entando/entando/aps/system/init/model/portdb/UserPreferences.java
  src/main/java/org/entando/entando/aps/system/init/model/servdb/User.java
  src/main/java/org/entando/entando/aps/system/services/user/IUserService.java
  src/main/java/org/entando/entando/aps/system/services/user/UserService.java
  src/main/java/org/entando/entando/aps/system/services/user/model/UserDto.java
  src/main/java/org/entando/entando/aps/system/services/userpreferences/IUserPreferencesDAO.java
  src/main/java/org/entando/entando/aps/system/services/userpreferences/IUserPreferencesManager.java
  src/main/java/org/entando/entando/aps/system/services/userpreferences/IUserPreferencesService.java
  src/main/java/org/entando/entando/aps/system/services/userpreferences/UserPreferences.java
  src/main/java/org/entando/entando/aps/system/services/userpreferences/UserPreferencesDAO.java
  src/main/java/org/entando/entando/aps/system/services/userpreferences/UserPreferencesManager.java
  src/main/java/org/entando/entando/aps/system/services/userpreferences/UserPreferencesService.java
  src/main/java/org/entando/entando/web/user/UserController.java
  src/main/java/org/entando/entando/web/user/model/UserRequest.java
  src/main/java/org/entando/entando/web/user/model/UserWizardRequest.java
  src/main/java/org/entando/entando/web/user/validator/UserValidator.java
  src/main/java/org/entando/entando/web/userpreferences/UserPreferencesController.java
  src/main/java/org/entando/entando/web/userpreferences/model/UserPreferencesDto.java
  src/main/java/org/entando/entando/web/userpreferences/model/UserPreferencesRequest.java
  src/main/java/org/entando/entando/web/userpreferences/validator/UserPreferencesValidator.java
  src/main/resources/rest/messages.properties
  src/main/resources/spring/aps/dao/daoConfig.xml
  src/main/resources/spring/aps/managers/baseManagersConfig.xml
  src/main/resources/spring/aps/servicesConfig.xml
  src/main/resources/spring/baseSystemConfig.xml
  src/main/resources/sql/entandoServ_data_production.sql
  src/test/java/com/agiletec/aps/ControllersAllTests.java
  src/test/java/org/entando/entando/web/user/1_POST_user_with_default_profile.json
  src/test/java/org/entando/entando/web/user/1_POST_user_wizard_disabled.json
  src/test/java/org/entando/entando/web/user/1_POST_user_wizard_enabled.json
  src/test/java/org/entando/entando/web/user/1_PUT_user_with_profile.json
  src/test/java/org/entando/entando/web/user/UserControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/userpreferences/1_PUT_user_preferences.json
  src/test/java/org/entando/entando/web/userpreferences/2_PUT_user_preferences.json
  src/test/java/org/entando/entando/web/userpreferences/3_PUT_user_preferences.json
  src/test/java/org/entando/entando/web/userpreferences/4_PUT_user_preferences.json
  src/test/java/org/entando/entando/web/userpreferences/5_PUT_user_preferences.json
  src/test/java/org/entando/entando/web/userpreferences/6_PUT_user_preferences.json
  src/test/java/org/entando/entando/web/userpreferences/7_PUT_user_preferences.json
  src/test/java/org/entando/entando/web/userpreferences/8_PUT_user_preferences.json
  src/test/java/org/entando/entando/web/userpreferences/UserPreferencesControllerIntegrationTest.java
  src/test/resources/sql/entandoServ_data_test.sql
Labels: approved, size/XXL

#67 ENG-1171: Fix random failures when saving contents
  src/main/java/com/agiletec/aps/system/common/entity/model/ApsEntity.java
  src/main/java/com/agiletec/aps/system/common/entity/model/IApsEntity.java
  src/main/java/com/agiletec/aps/system/common/entity/model/attribute/AbstractAttribute.java
  src/main/java/com/agiletec/aps/system/common/entity/model/attribute/AttributeInterface.java
  src/main/java/com/agiletec/aps/system/common/entity/model/attribute/CompositeAttribute.java
  src/main/java/com/agiletec/aps/system/common/entity/model/attribute/DateAttribute.java
  src/main/java/com/agiletec/aps/system/common/entity/model/attribute/ListAttribute.java
  src/main/java/com/agiletec/aps/system/common/entity/model/attribute/MonoListAttribute.java
  src/main/java/com/agiletec/aps/system/common/entity/model/attribute/NumberAttribute.java
  src/main/java/com/agiletec/aps/system/common/entity/model/attribute/TimestampAttribute.java
  src/main/java/org/entando/entando/aps/system/services/dataobject/api/ApiDataObjectInterface.java
  src/main/java/org/entando/entando/aps/system/services/entity/AbstractEntityService.java
  src/main/java/org/entando/entando/aps/system/services/userprofile/api/ApiUserProfileInterface.java
  src/main/resources/spring/aps/managers/dataManagersConfig.xml
  src/main/resources/spring/aps/managers/userprofileManagers.xml
  src/test/java/com/agiletec/aps/AllTests.java
  src/test/java/org/entando/entando/aps/system/services/dataobject/TestValidateDataObject.java
  src/test/java/org/entando/entando/aps/system/services/entity/EntityManagerServiceIntegrationTest.java
  src/test/java/org/entando/entando/aps/system/services/userprofile/TestApiUserProfileInterface.java
  src/test/java/org/entando/entando/aps/system/services/userprofile/UserProfileManagerIntegrationTest.java
  src/test/java/org/entando/entando/aps/system/services/userprofile/ValidateUserProfileIntegrationTest.java
  src/test/java/org/entando/entando/web/userprofile/ProfileTypeControllerIntegrationTest.java
  src/test/resources/sql/entandoPort_data_test.sql
  src/test/resources/sql/entandoServ_data_test.sql
Labels: approved, size/XXL

#73 ENG-963 Making createFullPath public
  src/main/java/org/entando/entando/aps/system/services/storage/IStorageManager.java
  src/main/java/org/entando/entando/aps/system/services/storage/LocalStorageManager.java
Labels: approved, size/XS

#72 ENG-1395 Adds support for cms assets and contents correlation using code
  src/main/db/update/scriptPort.sql
  src/main/resources/rest/messages.properties
Labels: size/XS

#75 ENG-1387: Added test for user profile with email attribute
  src/test/java/org/entando/entando/web/userprofile/9_POST_valid.json
  src/test/java/org/entando/entando/web/userprofile/UserProfileControllerIntegrationTest.java
Labels: approved, size/M

#76 ENG-1244 refactor to readonlyPageWidgetConfig
  src/main/db/update/scriptPort.sql
  src/main/java/org/entando/entando/aps/system/init/model/portdb/WidgetCatalog.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/IWidgetTypeDAO.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/IWidgetTypeManager.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetService.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetType.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetTypeDAO.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetTypeManager.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/api/ApiWidgetTypeInterface.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/api/JAXBWidgetType.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/model/WidgetDto.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/model/WidgetDtoBuilder.java
  src/main/java/org/entando/entando/web/page/validator/PageConfigurationValidator.java
  src/main/java/org/entando/entando/web/widget/model/WidgetRequest.java
  src/main/resources/sql/entandoPort_data_production.sql
  src/test/java/com/agiletec/aps/system/services/widgettype/TestWidgetTypeManager.java
  src/test/java/org/entando/entando/aps/system/services/userprofile/TestApiUserProfileInterface.java
  src/test/java/org/entando/entando/aps/system/services/widgettype/WidgetServiceTest.java
  src/test/java/org/entando/entando/aps/system/services/widgettype/api/TestApiWidgetTypeInterface.java
  src/test/java/org/entando/entando/web/page/PageConfigurationControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/widget/WidgetControllerIntegrationTest.java
  src/test/resources/sql/entandoPort_data_test.sql
Labels: approved, size/L

#74 ENG-1395 Implement support class (RestNamedId) for polimorfic ID in rest calls
  src/main/java/org/entando/entando/web/common/model/RestNamedId.java
  src/test/java/com/agiletec/aps/AllTests.java
  src/test/java/org/entando/entando/web/common/model/RestNamedIdTest.java
Labels: approved, size/L
