Repository entando/entando-engine, pull requests merged in 2020-07, with the labels that each got.

#4 Eng 827 finalization of new pipelines
  pom.xml
  src/main/java/com/agiletec/aps/system/services/health/HealthDAO.java
  src/main/java/com/agiletec/aps/system/services/health/IHealthDAO.java
  src/main/java/org/entando/entando/aps/system/services/health/HealthService.java
  src/main/java/org/entando/entando/aps/system/services/health/IHealthService.java
  src/main/java/org/entando/entando/aps/system/services/page/PageAuthorizationService.java
  src/main/java/org/entando/entando/aps/system/services/page/PageService.java
  src/main/java/org/entando/entando/web/category/CategoryController.java
  src/main/java/org/entando/entando/web/common/handlers/RestExceptionHandler.java
  src/main/java/org/entando/entando/web/dashboard/DashboardController.java
  src/main/java/org/entando/entando/web/filebrowser/validator/FileBrowserValidator.java
  src/main/java/org/entando/entando/web/group/GroupController.java
  src/main/java/org/entando/entando/web/health/HealthController.java
  src/main/java/org/entando/entando/web/language/LanguageController.java
  src/main/java/org/entando/entando/web/page/PageConfigurationController.java
  src/main/java/org/entando/entando/web/page/PageController.java
  src/main/java/org/entando/entando/web/pagemodel/PageModelController.java
  src/main/java/org/entando/entando/web/pagesettings/PageSettingsController.java
  src/main/java/org/entando/entando/web/role/RoleController.java
  src/main/java/org/entando/entando/web/user/UserController.java
  src/main/java/org/entando/entando/web/userprofile/ProfileController.java
  src/main/java/org/entando/entando/web/userprofile/ProfileTypeController.java
  src/main/java/org/entando/entando/web/widget/WidgetController.java
  src/main/resources/spring/aps/dao/daoConfig.xml
  src/main/resources/spring/aps/servicesConfig.xml
  src/test/java/com/agiletec/aps/system/services/health/HealthDAOTest.java
  src/test/java/org/entando/entando/aps/system/services/health/HealthServiceTest.java
  src/test/java/org/entando/entando/web/category/CategoryControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/category/CategoryControllerTest.java
  src/test/java/org/entando/entando/web/dashboard/DashboardControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/filebrowser/FileBrowserControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/group/GroupControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/health/HealthControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/health/HealthControllerTest.java
  src/test/java/org/entando/entando/web/language/LanguageControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/page/PageControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/page/PageControllerTest.java
  src/test/java/org/entando/entando/web/pagemodel/PageModelControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/pagesettings/PageSettingsControllerTest.java
  src/test/java/org/entando/entando/web/user/UserControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/userprofile/UserProfileControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/widget/WidgetControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/widget/WidgetControllerTest.java
Labels: approved, size/XL

#5 ENG-683 Changing endpoint permissions
  src/main/java/org/entando/entando/web/category/CategoryController.java
  src/main/java/org/entando/entando/web/group/GroupController.java
  src/main/java/org/entando/entando/web/user/UserController.java
  src/test/java/org/entando/entando/web/category/CategoryControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/category/CategoryControllerTest.java
  src/test/java/org/entando/entando/web/group/GroupControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/user/UserControllerIntegrationTest.java
Labels: size/M

#7 ENG-787 appBuilderIntegrationEnabled flag and appBuilderBaseURL added
  src/main/resources/spring/aps/managers/baseManagersConfig.xml
  src/test/config/conf/systemParams.properties
Labels: approved, size/S

#6 ENG-877: Add LICENSE file
  LICENSE
Labels: approved, size/L

#8 ENG-681/ENG-800: Extend the getPages API for taking into account "linkability"
  pom.xml
  src/main/java/org/entando/entando/aps/system/services/page/IPageService.java
  src/main/java/org/entando/entando/aps/system/services/page/PageService.java
  src/main/java/org/entando/entando/aps/util/GenericResourceUtils.java
  src/main/java/org/entando/entando/web/page/PageController.java
  src/test/java/org/entando/entando/aps/system/services/page/PageServiceTest.java
  src/test/java/org/entando/entando/aps/util/GenericResourceUtilsTest.java
  src/test/java/org/entando/entando/web/page/PageControllerTest.java
  src/test/resources/controllers/pages/essential-page-tree.json
  src/test/resources/controllers/pages/simple-page-tree-with-multiple-groups.json
Labels: approved, size/XL

#9 ENG-477: Added "onlineInstance" property into PageDto
  src/main/java/org/entando/entando/aps/system/services/page/model/PageDto.java
  src/test/java/org/entando/entando/web/page/PageControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/pagemodel/PageModelControllerIntegrationTest.java
Labels: approved, size/M

#10 ENG-800: Remove unintentional POM changes
  pom.xml
Labels: approved, size/XS

#11 ENG-889: Add dependency to org.apache.taglibs
  pom.xml
Labels: approved, size/XS

#12 ENG-878 Cannot delete root category
  src/main/java/org/entando/entando/aps/system/services/category/CategoryService.java
  src/main/java/org/entando/entando/web/category/validator/CategoryValidator.java
  src/main/resources/rest/messages.properties
  src/test/java/org/entando/entando/web/category/CategoryControllerIntegrationTest.java
Labels: size/S

#13 ENG-773 Changed method access modifier
  src/main/java/org/entando/entando/aps/system/services/page/PageService.java
Labels: approved, size/XS

#15 ENG-773 Changed method access modifier from private to protected for new SEO PUT API
  src/main/java/org/entando/entando/aps/system/services/page/PageService.java
Labels: approved, size/XS

#14 ENG-415
  src/main/java/org/entando/entando/aps/system/services/guifragment/GuiFragmentService.java
  src/main/java/org/entando/entando/aps/system/services/page/PageService.java
  src/main/java/org/entando/entando/aps/system/services/pagemodel/PageModelService.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetService.java
  src/test/java/org/entando/entando/aps/system/services/guifragment/GuiFragmentServiceTest.java
  src/test/java/org/entando/entando/aps/system/services/page/PageServiceTest.java
  src/test/java/org/entando/entando/aps/system/services/pagemodel/PageModelServiceTest.java
  src/test/java/org/entando/entando/aps/system/services/widgettype/WidgetServiceTest.java
Labels: size/M

#17 ENG-948 fix for autowiring the correct page service
  src/main/java/org/entando/entando/web/page/PageController.java
Labels: approved, size/XS

#16 ENG-927: API to map navigation data structure to navigation expression
  src/main/java/com/agiletec/aps/system/services/page/widget/NavigatorExpression.java
  src/main/java/com/agiletec/aps/system/services/page/widget/NavigatorParser.java
  src/main/java/org/entando/entando/web/widget/NavigatorWidgetConfigController.java
  src/main/java/org/entando/entando/web/widget/model/NavigatorConfigDto.java
  src/main/java/org/entando/entando/web/widget/model/NavigatorExpressionDto.java
  src/main/java/org/entando/entando/web/widget/validator/NavigatorWidgetConfigValidator.java
  src/main/resources/rest/messages.properties
  src/test/java/com/agiletec/aps/ControllersAllTests.java
  src/test/java/org/entando/entando/web/widget/NavigatorWidgetConfigControllerIntegrationTest.java
Labels: size/XL

#18 ENG-948 fixed issues with Bean conflicts
  src/main/java/org/entando/entando/web/page/PageController.java
  src/main/resources/spring/aps/servicesConfig.xml
Labels: approved, size/XS

#20 ENG-947: Improvement of existing API for fetching widget's simple config parameters
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetService.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/model/WidgetDto.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/model/WidgetDtoBuilder.java
  src/main/java/org/entando/entando/web/widget/WidgetController.java
  src/test/java/org/entando/entando/web/widget/WidgetControllerIntegrationTest.java
Labels: size/M

#21 ENG-970 clear group list before adding the new ones
  src/main/java/com/agiletec/aps/system/common/entity/model/ApsEntity.java
  src/main/java/com/agiletec/aps/system/common/entity/model/IApsEntity.java
  src/main/java/org/entando/entando/aps/system/services/entity/model/EntityDto.java
Labels: approved, size/S
