Repository entando/entando-engine, pull requests merged in 2020-12, with the labels that each got.

#91 ENG-1513 Nonce Injection (also includes ENG-1579)
  pom.xml
  src/main/java/org/entando/entando/aps/system/services/guifragment/GuiFragmentService.java
  src/main/java/org/entando/entando/aps/system/services/pagemodel/PageModelService.java
  src/main/java/org/entando/entando/aps/system/services/security/NonceInjector.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetService.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/model/WidgetDto.java
  src/test/java/com/agiletec/aps/AllTests.java
  src/test/java/org/entando/entando/aps/system/services/guifragment/FragmentTestUtil.java
  src/test/java/org/entando/entando/aps/system/services/guifragment/GuiFragmentServiceTest.java
  src/test/java/org/entando/entando/aps/system/services/mockhelper/FragmentMockHelper.java
  src/test/java/org/entando/entando/aps/system/services/pagemodel/PageModelServiceTest.java
  src/test/java/org/entando/entando/aps/system/services/pagemodel/PageModelTestUtil.java
  src/test/java/org/entando/entando/aps/system/services/security/NonceInjectorTest.java
  src/test/java/org/entando/entando/aps/system/services/widgettype/WidgetServiceTest.java
Labels: approved, size/L

#92 ENG-1576: Workaround windows startup issue caused by mixed path separ…
  src/main/java/org/entando/entando/aps/system/services/storage/LocalStorageManager.java
  src/main/java/org/entando/entando/aps/system/services/storage/StorageManagerUtil.java
  src/test/java/org/entando/entando/aps/system/services/storage/StorageManagerUtilTest.java
Labels: approved, size/M

#93 ENG-1566 validation changed if widget type config is read only
  src/main/java/org/entando/entando/web/page/validator/PageConfigurationValidator.java
  src/test/java/org/entando/entando/web/page/PageConfigurationControllerIntegrationTest.java
Labels: approved, size/S

#94 ENG-1638 added automatic aps-core lib tag injection when injecting nonce
  src/main/java/org/entando/entando/aps/system/services/security/NonceInjector.java
  src/test/java/org/entando/entando/aps/system/services/guifragment/GuiFragmentServiceTest.java
  src/test/java/org/entando/entando/aps/system/services/pagemodel/PageModelServiceTest.java
  src/test/java/org/entando/entando/aps/system/services/security/NonceInjectorTest.java
  src/test/java/org/entando/entando/aps/system/services/widgettype/WidgetServiceTest.java
Labels: size/M

#95 PARENT_POM_UPDATE-2020-12-10_22-12-04
  pom.xml
Labels: size/XS

#97 ENG-864 add XY and overlapping frames validations
  src/main/java/org/entando/entando/web/pagemodel/PageModelController.java
  src/main/java/org/entando/entando/web/pagemodel/validator/PageModelValidator.java
  src/main/resources/rest/messages.properties
  src/test/java/org/entando/entando/aps/system/services/pagemodel/PageModelTestUtil.java
  src/test/java/org/entando/entando/web/pagemodel/1_POST_valid_frames.json
  src/test/java/org/entando/entando/web/pagemodel/2_POST_valid_frames.json
  src/test/java/org/entando/entando/web/pagemodel/PageModelControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/pagemodel/PageModelControllerTest.java
  src/test/java/org/entando/entando/web/pagemodel/invalid_Y1Y2_frames_1.json
  src/test/java/org/entando/entando/web/pagemodel/invalid_Y1Y2_frames_2.json
  src/test/java/org/entando/entando/web/pagemodel/invalid_Y1Y2_frames_3.json
  src/test/java/org/entando/entando/web/pagemodel/invalid_Y1Y2_frames_4.json
  src/test/java/org/entando/entando/web/pagemodel/invalid_Y1Y2_frames_5.json
  src/test/java/org/entando/entando/web/pagemodel/invalid_Y1Y2_frames_6.json
  src/test/java/org/entando/entando/web/pagemodel/overlapping_frames_1.json
  src/test/java/org/entando/entando/web/pagemodel/overlapping_frames_2.json
Labels: approved, size/XL

#99 ENG-1578 delete resource error messages added
  src/main/resources/rest/messages.properties
Labels: approved, size/XS

#100 ENG-1608 Null check in date fields in validation rules amended
  src/main/java/org/entando/entando/aps/system/services/entity/model/EntityTypeAttributeValidationDto.java
  src/test/java/org/entando/entando/web/dataobject/5_PUT_valid_date_validation_1.json
  src/test/java/org/entando/entando/web/dataobject/5_PUT_valid_date_validation_2.json
  src/test/java/org/entando/entando/web/dataobject/5_PUT_valid_date_validation_3.json
  src/test/java/org/entando/entando/web/dataobject/DataTypeControllerIntegrationTest.java
Labels: approved, size/L
