Repository entando/entando-engine, pull requests merged in 2020-08, with the labels that each got.

#22 ENG-989: Fix page status
  src/main/java/com/agiletec/aps/system/services/page/cache/PageManagerCacheWrapper.java
Labels: approved, size/S

#19 ENG-761: Implemented CSRF filter
  src/main/java/com/agiletec/aps/system/SystemConstants.java
  src/main/java/org/entando/entando/aps/servlet/StartupListener.java
  src/main/java/org/entando/entando/aps/servlet/security/CsrfFilter.java
  src/main/java/org/entando/entando/aps/servlet/security/SecurityWebApplicationInitializer.java
  src/main/java/org/entando/entando/aps/system/exception/CSRFProtectionException.java
  src/test/java/com/agiletec/aps/AllTests.java
  src/test/java/org/entando/entando/aps/servlet/security/CsrfFilterTest.java
Labels: ok-to-test, size/L

#24 ENG-997 hitting the restore button the page status is correctly updated
  src/main/java/com/agiletec/aps/system/services/page/cache/PageManagerCacheWrapper.java
Labels: size/S

#25 ENG-912 Widget APIs with parentType and parameters
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetService.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetType.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetTypeParameter.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/model/WidgetDto.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/model/WidgetDtoBuilder.java
  src/main/java/org/entando/entando/web/widget/model/WidgetRequest.java
  src/main/java/org/entando/entando/web/widget/validator/WidgetValidator.java
  src/test/java/org/entando/entando/web/widget/WidgetControllerIntegrationTest.java
Labels: size/L

#26 ENG-912 Fixed issues on widget create/update with parentType and parameters
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetService.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/model/WidgetDto.java
  src/main/java/org/entando/entando/web/widget/model/WidgetRequest.java
  src/test/java/org/entando/entando/web/widget/WidgetControllerIntegrationTest.java
Labels: size/M

#29 ENG-912 widget with parameters config values
  src/main/java/com/agiletec/aps/util/ApsProperties.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetService.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/model/WidgetDto.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/model/WidgetDtoBuilder.java
  src/main/java/org/entando/entando/web/widget/model/WidgetRequest.java
  src/test/java/org/entando/entando/web/widget/WidgetControllerIntegrationTest.java
  src/test/resources/sql/entandoPort_data_test.sql
Labels: size/L

#30 ENG-986 added entity comparators
  src/main/java/org/entando/entando/aps/system/services/entity/model/AttributePropertyDto.java
  src/main/java/org/entando/entando/aps/system/services/entity/model/EntityTypeAttributeDto.java
Labels: size/M
