Repository entando/entando-engine, pull requests merged in 2020-11, with the labels that each got.

#77 ENG-1276 new widgetCategory field added
  src/main/db/update/scriptPort.sql
  src/main/java/org/entando/entando/aps/system/init/model/portdb/WidgetCatalog.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/IWidgetTypeDAO.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/IWidgetTypeManager.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetService.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetType.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetTypeDAO.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetTypeManager.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/api/ApiWidgetTypeInterface.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/api/JAXBWidgetType.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/model/WidgetDto.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/model/WidgetDtoBuilder.java
  src/main/java/org/entando/entando/web/widget/model/WidgetRequest.java
  src/main/resources/sql/entandoPort_data_production.sql
  src/test/java/com/agiletec/aps/AllTests.java
  src/test/java/com/agiletec/aps/system/services/widgettype/TestWidgetType.java
  src/test/java/com/agiletec/aps/system/services/widgettype/TestWidgetTypeDAO.java
  src/test/java/com/agiletec/aps/system/services/widgettype/TestWidgetTypeManager.java
  src/test/java/org/entando/entando/aps/system/services/widgettype/WidgetServiceTest.java
  src/test/java/org/entando/entando/web/page/PageConfigurationControllerIntegrationTest.java
  src/test/resources/sql/entandoPort_data_test.sql
Labels: approved, size/L

#78 ENG-1452 Fixing user preferences type conversion for postgresql
  src/main/java/org/entando/entando/aps/system/services/userpreferences/UserPreferencesDAO.java
Labels: approved, size/S

#79 ENG-1386: Added integration tests for ProfileTypeController
  src/test/java/org/entando/entando/web/userprofile/10_PUT_attribute_valid_1.json
  src/test/java/org/entando/entando/web/userprofile/10_PUT_attribute_valid_2.json
  src/test/java/org/entando/entando/web/userprofile/ProfileTypeControllerIntegrationTest.java
Labels: approved, size/L

#82 ENG-1452 Also fixing the update conversion for PostgreSQL
  src/main/java/org/entando/entando/aps/system/services/userpreferences/UserPreferencesDAO.java
Labels: approved, size/XS

#80 ENG-1398: Added new api for profile type attributes
  src/main/java/org/entando/entando/aps/system/services/entity/AbstractEntityTypeService.java
  src/main/java/org/entando/entando/aps/system/services/entity/model/AttributeTypeDto.java
  src/main/java/org/entando/entando/aps/system/services/userprofile/IUserProfileTypeService.java
  src/main/java/org/entando/entando/aps/system/services/userprofile/UserProfileTypeService.java
  src/main/java/org/entando/entando/web/userprofile/ProfileTypeController.java
  src/test/java/org/entando/entando/web/userprofile/ProfileTypeControllerIntegrationTest.java
Labels: size/M

#83 ENG-1449 remove ootb users approver and editor
  src/main/resources/sql/entandoServ_data_production.sql
Labels: approved, size/XS

#85 ENG-1474 validation change for uppercase username
  src/main/java/org/entando/entando/web/user/validator/UserValidator.java
  src/main/resources/rest/messages.properties
  src/test/java/org/entando/entando/web/user/UserControllerIntegrationTest.java
Labels: approved, lgtm, size/S

#86 ENG-1502 page template main frame fix using app builder flow
  src/main/java/org/entando/entando/aps/system/services/pagemodel/PageModelService.java
  src/test/java/org/entando/entando/aps/system/services/pagemodel/PageModelServiceTest.java
Labels: approved, size/S

#81 ENG-1327/ENG-1441 add to the entandoengine api to check existence of a set of components
  src/main/java/org/entando/entando/aps/system/services/IComponentExistsService.java
  src/main/java/org/entando/entando/aps/system/services/analysis/component_existence/ComponentExistenceAnalysis.java
  src/main/java/org/entando/entando/aps/system/services/category/CategoryService.java
  src/main/java/org/entando/entando/aps/system/services/category/ICategoryService.java
  src/main/java/org/entando/entando/aps/system/services/entity/AbstractEntityTypeService.java
  src/main/java/org/entando/entando/aps/system/services/group/GroupService.java
  src/main/java/org/entando/entando/aps/system/services/group/IGroupService.java
  src/main/java/org/entando/entando/aps/system/services/guifragment/GuiFragmentService.java
  src/main/java/org/entando/entando/aps/system/services/guifragment/IGuiFragmentService.java
  src/main/java/org/entando/entando/aps/system/services/label/ILabelService.java
  src/main/java/org/entando/entando/aps/system/services/label/LabelService.java
  src/main/java/org/entando/entando/aps/system/services/language/ILanguageService.java
  src/main/java/org/entando/entando/aps/system/services/language/LanguageService.java
  src/main/java/org/entando/entando/aps/system/services/page/IPageService.java
  src/main/java/org/entando/entando/aps/system/services/page/PageService.java
  src/main/java/org/entando/entando/aps/system/services/pagemodel/IPageModelService.java
  src/main/java/org/entando/entando/aps/system/services/pagemodel/PageModelService.java
  src/main/java/org/entando/entando/aps/system/services/storage/FileBrowserService.java
  src/main/java/org/entando/entando/aps/system/services/storage/IFileBrowserService.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/IWidgetService.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetService.java
  src/main/java/org/entando/entando/web/analysis/AnalysisController.java
  src/main/java/org/entando/entando/web/analysis/AnalysisResponse.java
  src/main/java/org/entando/entando/web/analysis/IAnalysisController.java
  src/main/java/org/entando/entando/web/filebrowser/validator/FileBrowserValidator.java
  src/main/resources/rest/messages.properties
  src/test/java/com/agiletec/aps/AllTests.java
  src/test/java/com/agiletec/aps/ControllersAllTests.java
  src/test/java/com/agiletec/aps/ServicesAllTests.java
  src/test/java/org/entando/entando/aps/system/services/analysis/component_existence/ComponentExistenceAnalysisTest.java
  src/test/java/org/entando/entando/web/AbstractControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/analysis/AnalysisControllerDiffAnalysisEngineTestsStubs.java
  src/test/java/org/entando/entando/web/analysis/AnalysisControllerTest.java
  src/test/java/org/entando/entando/web/category/CategoryControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/filebrowser/FileBrowserControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/group/GroupControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/guifragment/GuiFragmentControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/label/LabelControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/language/LanguageControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/page/PageControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/pagemodel/PageModelControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/widget/WidgetControllerIntegrationTest.java
Labels: do-not-merge/work-in-progress, size/XXL

#89 ENG-1366 add newline char manually in for clob types in db backup
  src/main/java/org/entando/entando/aps/system/init/util/TableDataUtils.java
Labels: approved, size/XS

#90 Fix noise and incorrect logging behaviour in AppEngine
  pom.xml
  src/main/java/com/agiletec/aps/system/ApsSystemUtils.java
  src/main/java/com/agiletec/aps/system/services/page/PageManager.java
  src/main/java/org/entando/entando/aps/servlet/StartupListener.java
  src/main/java/org/entando/entando/aps/system/init/DatabaseManager.java
  src/main/java/org/entando/entando/aps/system/init/SelfRestCaller.java
  src/main/java/org/entando/entando/aps/system/init/util/TableFactory.java
  src/main/java/org/entando/entando/web/common/model/Filter.java
  src/main/java/org/entando/entando/web/user/model/UserPasswordRequest.java
  src/test/java/com/agiletec/aps/system/services/widgettype/TestWidgetTypeDAO.java
  src/test/java/org/entando/entando/ent/util/EntLoggingTest.java
  src/test/java/org/entando/entando/web/AbstractControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/activitystream/ActivityStreamControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/api/oauth2/ApiConsumerControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/category/CategoryControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/filebrowser/FileBrowserControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/group/GroupControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/guifragment/GuiFragmentControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/label/LabelControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/page/PageControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/pagemodel/PageModelControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/user/UserControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/userpreferences/UserPreferencesControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/userprofile/ProfileTypeControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/userprofile/UserProfileControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/widget/WidgetControllerIntegrationTest.java
  src/test/resources/log4j2.xml
Labels: approved, size/L

#87 ENG-1512: XSS protection using content security policies
  src/main/java/com/agiletec/aps/system/SystemConstants.java
  src/main/java/org/entando/entando/aps/tags/CspNonceTag.java
  src/main/resources/spring/aps/managers/baseManagersConfig.xml
  src/main/resources/sql/entandoPort_data_production.sql
  src/main/tld/aps-core.tld
  src/test/config/conf/systemParams.properties
  src/test/java/com/agiletec/aps/AllTests.java
  src/test/java/org/entando/entando/aps/system/init/util/guifragment.sql
  src/test/java/org/entando/entando/aps/tags/CspNonceTagTest.java
Labels: approved, size/L

#88 ENG-1075: fix new XSS and path-traversal vulnerabilities
  pom.xml
  src/main/java/com/agiletec/aps/system/exception/EntRuntimeException.java
  src/main/java/com/agiletec/aps/system/services/page/PageDAO.java
  src/main/java/com/agiletec/aps/system/services/url/URLManager.java
  src/main/java/com/agiletec/aps/system/services/user/UserDAO.java
  src/main/java/com/agiletec/aps/tags/ActionURLTag.java
  src/main/java/com/agiletec/aps/tags/PageInfoTag.java
  src/main/java/com/agiletec/aps/tags/URLTag.java
  src/main/java/com/agiletec/aps/util/FileTextReader.java
  src/main/java/org/entando/entando/aps/servlet/security/OAuth2SecurityConfiguration.java
  src/main/java/org/entando/entando/aps/system/init/DatabaseManager.java
  src/main/java/org/entando/entando/aps/system/services/oauth2/ApiOAuth2TokenManager.java
  src/main/java/org/entando/entando/aps/system/services/page/PageTokenManager.java
  src/main/java/org/entando/entando/aps/system/services/storage/IStorageManager.java
  src/main/java/org/entando/entando/aps/system/services/storage/LocalStorageManager.java
  src/main/java/org/entando/entando/aps/system/services/storage/StorageManagerUtil.java
  src/main/java/org/entando/entando/aps/util/crypto/CompatiblePasswordEncoder.java
  src/main/java/org/entando/entando/ent/util/EntLogging.java
  src/test/java/com/agiletec/aps/AllTests.java
  src/test/java/com/agiletec/aps/tags/PageInfoTagTest.java
  src/test/java/com/agiletec/aps/util/FileTextReaderTest.java
  src/test/java/org/entando/entando/aps/system/services/page/PageTokenManagerTest.java
  src/test/java/org/entando/entando/aps/system/services/pagemodel/PageModelDtoTest.java
  src/test/java/org/entando/entando/aps/system/services/storage/LocalStorageManagerIntegrationTest.java
  src/test/java/org/entando/entando/aps/system/services/storage/StorageManagerUtilTest.java
  src/test/java/org/entando/entando/web/filebrowser/FileBrowserControllerIntegrationTest.java
Labels: do-not-merge/work-in-progress, size/XL
