Repository entando/entando-engine, pull requests merged in 2021-05, with the labels that each got.

#143 ENG-2289 Updating my group permission path
  jenkins-x.yml
  src/main/java/org/entando/entando/web/user/UserController.java
  src/test/java/org/entando/entando/web/user/UserControllerIntegrationTest.java
Labels: approved, size/M

#144 ENG-2254 Decoding url param currentPath
  src/main/java/org/entando/entando/aps/system/services/storage/StorageManagerUtil.java
  src/main/java/org/entando/entando/web/filebrowser/FileBrowserController.java
  src/test/java/org/entando/entando/web/filebrowser/FileBrowserControllerIntegrationTest.java
Labels: approved, size/L

#146 ENG-2254 Fix deleting file with spaces
  src/main/java/org/entando/entando/aps/system/services/storage/FileBrowserService.java
  src/main/java/org/entando/entando/aps/system/services/storage/StorageManagerUtil.java
  src/main/java/org/entando/entando/web/filebrowser/FileBrowserController.java
  src/test/java/org/entando/entando/aps/system/services/storage/StorageManagerUtilTest.java
  src/test/java/org/entando/entando/web/filebrowser/FileBrowserControllerIntegrationTest.java
Labels: approved, size/L

#137 ENG-2263: Added 'escapeAmp' parameter in URLTag
  src/main/java/com/agiletec/aps/tags/URLTag.java
  src/main/tld/aps-core.tld
Labels: approved, size/S

#147 ENG-2366 Validating page placement
  src/main/java/org/entando/entando/web/page/PageController.java
  src/main/java/org/entando/entando/web/page/validator/PageValidator.java
  src/test/java/org/entando/entando/web/page/PageControllerIntegrationTest.java
Labels: approved, size/L
