Repository entando/entando-engine, pull requests merged in 2021-04, with the labels that each got.

#127 ENG-2037: Fix security issues
  src/main/java/com/agiletec/aps/util/FileTextReader.java
  src/main/java/org/entando/entando/aps/system/services/storage/FileBrowserService.java
Labels: approved, size/M

#130 #ENG-2112 Fixing /myProfileType endpoint, user without profile
  src/main/java/org/entando/entando/web/userprofile/ProfileTypeController.java
  src/main/resources/sql/entandoPort_data_production.sql
  src/test/java/org/entando/entando/web/userprofile/ProfileTypeControllerIntegrationTest.java
Labels: approved, size/M

#132 ENG-2037: Fix security issues
  src/main/java/com/agiletec/aps/util/FileTextReader.java
  src/main/java/org/entando/entando/aps/system/services/database/DatabaseService.java
  src/main/java/org/entando/entando/aps/system/services/storage/FileBrowserService.java
Labels: approved, size/M

#133 ENG-2037: other security fix into FileTextReader
  src/main/java/com/agiletec/aps/util/FileTextReader.java
Labels: size/XS

#134 ENG-2037: Fix security issues
  src/main/java/com/agiletec/aps/util/FileTextReader.java
Labels: approved, size/XS

#136 ENG-2261: upgrade velocity version
  pom.xml
  src/main/java/com/agiletec/aps/system/common/entity/model/attribute/AbstractTextAttribute.java
  src/main/java/com/agiletec/aps/system/common/entity/model/attribute/HypertextAttribute.java
  src/main/java/com/agiletec/aps/system/common/renderer/BaseEntityRenderer.java
  src/main/java/com/agiletec/aps/system/common/renderer/DefaultVelocityRenderer.java
  src/main/java/com/agiletec/aps/system/services/authorization/AuthorizationManager.java
  src/main/java/com/agiletec/aps/system/services/category/CategoryManager.java
  src/main/java/com/agiletec/aps/system/services/i18n/I18nManager.java
  src/main/java/com/agiletec/aps/system/services/i18n/wrapper/I18nLabelBuilder.java
  src/main/java/com/agiletec/aps/system/services/pagemodel/PageModelManager.java
  src/main/java/com/agiletec/aps/tags/CheckPermissionTag.java
  src/main/java/com/agiletec/aps/tags/PageWithWidgetTag.java
  src/main/java/org/entando/entando/aps/system/XmlWebApplicationContext.java
  src/main/java/org/entando/entando/aps/system/common/entity/model/attribute/EnumeratorMapAttribute.java
  src/main/java/org/entando/entando/aps/system/init/util/TableDataUtils.java
  src/main/java/org/entando/entando/aps/system/services/cache/CacheInfoManager.java
  src/main/java/org/entando/entando/aps/system/services/dataobject/widget/UserFilterOptionBean.java
  src/main/java/org/entando/entando/aps/system/services/dataobjectsearchengine/SearchEngineManager.java
  src/main/java/org/entando/entando/aps/system/services/entity/AbstractEntityTypeService.java
  src/main/java/org/entando/entando/aps/system/services/guifragment/GuiFragment.java
  src/main/java/org/entando/entando/aps/system/services/guifragment/GuiFragmentDAO.java
  src/main/java/org/entando/entando/aps/system/services/guifragment/api/ApiGuiFragmentInterface.java
  src/main/java/org/entando/entando/aps/system/services/page/PageTokenManager.java
  src/main/java/org/entando/entando/aps/system/services/storage/LocalStorageManager.java
  src/main/java/org/entando/entando/aps/system/services/storage/api/LocalStorageManagerInterface.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/api/ApiWidgetTypeInterface.java
  src/main/java/org/entando/entando/aps/tags/ExtendedTagSupport.java
  src/main/java/org/entando/entando/aps/tags/GuiFragmentTag.java
  src/main/java/org/entando/entando/web/common/model/RestEntityListRequest.java
  src/main/java/org/entando/entando/web/common/model/RestListRequest.java
  src/main/java/org/entando/entando/web/guifragment/validator/GuiFragmentValidator.java
  src/main/java/org/entando/entando/web/userpreferences/model/UserPreferencesDto.java
  src/test/java/org/entando/entando/web/MockMvcHelper.java
Labels: approved, size/L

#135 ENG-2259 Fix the vulnarable dependencies (ppom 6.3.9)
  pom.xml
Labels: approved, size/XS

#139 ENG-2236 Creating new endpoint myGroups
  pom.xml
  src/main/java/org/entando/entando/aps/system/services/user/IUserService.java
  src/main/java/org/entando/entando/aps/system/services/user/UserService.java
  src/main/java/org/entando/entando/web/user/UserController.java
  src/test/java/org/entando/entando/web/user/UserControllerIntegrationTest.java
Labels: approved, size/L

#138 ENG-2261: Fix velocity properties
  src/main/java/com/agiletec/aps/system/common/renderer/DefaultVelocityRenderer.java
Labels: size/XS

#140 ENG-2259: Other security fixes
  src/main/java/com/agiletec/aps/system/services/user/AuthenticationProviderManager.java
  src/main/java/org/entando/entando/aps/system/services/security/NonceInjector.java
  src/main/java/org/entando/entando/aps/util/crypto/CryptoBeansConfig.java
  src/main/java/org/entando/entando/aps/util/crypto/DefaultTextEncryptor.java
  src/main/java/org/entando/entando/web/system/ReloadConfigurationController.java
  src/test/java/org/entando/entando/aps/util/crypto/DefaultTextEncryptorTest.java
Labels: approved, size/L

#141 ENG-2029: Integration of logback
  pom.xml
  src/main/java/com/agiletec/aps/system/ApsSystemUtils.java
  src/main/java/org/entando/entando/ent/logger/EntRollingFileAppender.java
  src/main/java/org/entando/entando/ent/logger/EntThresholdFilter.java
  src/main/resources/log4j2.xml
  src/main/resources/logback.xml
  src/main/resources/spring/baseSystemConfig.xml
Labels: approved, size/L

#142 ENG-2251 accept "true" and "false" strings for BooleanAttribute value
  src/main/java/org/entando/entando/aps/system/services/entity/model/EntityAttributeDto.java
  src/test/java/org/entando/entando/aps/system/services/entity/model/EntityAttributeDtoTest.java
Labels: approved, size/M
