Repository entando/entando-engine, pull requests merged in 2021-07, with the labels that each got.

#156 ENG-2312: Upgrade Base Url Builder
  src/main/java/com/agiletec/aps/system/services/url/URLManager.java
Labels: approved, size/XS

#157 ENG-2312: Added new parameter ("baseUrlMode") into URLTag
  src/main/java/com/agiletec/aps/system/SystemConstants.java
  src/main/java/com/agiletec/aps/system/services/url/PageURL.java
  src/main/java/com/agiletec/aps/system/services/url/URLManager.java
  src/main/java/com/agiletec/aps/tags/URLTag.java
  src/main/tld/aps-core.tld
  src/test/java/com/agiletec/aps/system/services/url/URLManagerIntegrationTest.java
  src/test/java/com/agiletec/aps/system/services/url/URLManagerTest.java
Labels: approved, size/L

#158 ENG-2178: Fix Caches definitions
  src/main/resources/spring/aps/managers/baseManagersConfig.xml
Labels: approved, size/M

#159 ENG-2178 Fixing swagger ui
  pom.xml
Labels: approved, size/XS

#160 ENG-2172: Removed categories from entity objects
  src/main/java/com/agiletec/aps/system/common/entity/ApsEntityManager.java
  src/main/java/com/agiletec/aps/system/common/entity/model/ApsEntity.java
  src/main/java/com/agiletec/aps/system/common/entity/model/IApsEntity.java
  src/main/java/com/agiletec/aps/system/common/entity/model/JAXBEntity.java
  src/main/java/com/agiletec/aps/system/common/entity/parse/ApsEntityDOM.java
  src/main/java/com/agiletec/aps/system/common/entity/parse/EntityHandler.java
  src/main/java/com/agiletec/aps/system/common/entity/parse/IApsEntityDOM.java
  src/main/java/com/agiletec/aps/system/common/renderer/EntityWrapper.java
  src/main/java/org/entando/entando/aps/system/services/entity/AbstractEntityService.java
  src/main/java/org/entando/entando/aps/system/services/entity/model/EntityDto.java
  src/main/java/org/entando/entando/aps/system/services/userprofile/UserProfileManager.java
  src/main/java/org/entando/entando/aps/system/services/userprofile/api/ApiUserProfileInterface.java
  src/main/java/org/entando/entando/aps/system/services/userprofile/api/model/JAXBUserProfile.java
  src/main/resources/spring/aps/managers/entityManagerDef.xml
Labels: approved

#161 ENG-2178 Rolling back swagger version update
  pom.xml
  src/main/java/org/entando/entando/web/swagger/SwaggerConfig.java
Labels: size/S

#165 ENG-2471 GitHub action pipelines
  .github/workflows/ga-publication.yml
  .github/workflows/post-merge.yml
  .github/workflows/pr.yml
  .github/workflows/publication.yml
  jenkins-x.yml
Labels: prepared

#169 ENG-2471 Update README.md
  README.md
Labels: prepared

#171 ENG-2471 Support for ENTANDO_OPT_FEATURES secret
  .github/workflows/ga-publication.yml
  .github/workflows/post-merge.yml
  .github/workflows/pr.yml
  .github/workflows/publication.yml
  src/test/java/org/entando/entando/web/widget/WidgetControllerIntegrationTest.java
Labels: prepared

#170 ENG-2031: Improvement of EntityManager
  src/main/java/com/agiletec/aps/system/common/entity/ApsEntityManager.java
  src/main/java/com/agiletec/aps/system/common/entity/IEntityManager.java
  src/main/java/com/agiletec/aps/system/common/entity/parse/EntityTypeFactory.java
  src/main/java/com/agiletec/aps/system/common/entity/parse/IEntityTypeFactory.java
  src/test/java/org/entando/entando/aps/system/services/userprofile/UserProfileManagerIntegrationTest.java
Labels: prepared

#174 ENG-2178 Fixing swagger ui URL and suppressing snyk vulnerabilities
  .snyk
  pom.xml
  src/main/java/com/agiletec/aps/system/common/FieldSearchFilter.java
  src/main/java/com/agiletec/aps/system/common/entity/model/EntitySearchFilter.java
  src/main/java/org/entando/entando/web/common/model/Filter.java
  src/main/java/org/entando/entando/web/swagger/SwaggerConfig.java
Labels: approved, prepared

#175 ENG-2552: Remove Argon2 dependency
  README.md
  pom.xml
  src/main/java/com/agiletec/aps/system/services/baseconfig/BaseConfigManager.java
  src/main/java/com/agiletec/aps/system/services/baseconfig/ConfigInterface.java
  src/main/java/org/entando/entando/aps/util/crypto/Argon2PasswordEncoder.java
  src/main/java/org/entando/entando/aps/util/crypto/CompatiblePasswordEncoder.java
  src/main/java/org/entando/entando/aps/util/crypto/CryptoBeansConfig.java
  src/main/resources/spring/aps/managers/baseManagersConfig.xml
  src/test/config/conf/security.properties
  src/test/config/conf/systemParams.properties
  src/test/java/com/agiletec/aps/system/services/user/UserManagerTest.java
  src/test/java/org/entando/entando/aps/system/services/storage/LocalStorageManagerIntegrationTest.java
  src/test/java/org/entando/entando/aps/util/crypto/CompatiblePasswordEncoderTest.java
  src/test/java/org/entando/entando/web/filebrowser/FileBrowserControllerIntegrationTest.java
Labels: prepared

#176 ENG-2471 NewGen workflow v1.0.1
  .github/workflows/ga-publication.yml
  .github/workflows/post-merge.yml
  .github/workflows/pr.yml
  .github/workflows/publication.yml
Labels: prepared

#178 ENG-2471 NewGen workflow v1.0.1 - update to GA core parent 6.4.8
  pom.xml
Labels: prepared

#179 ENG-2554: Added properties in default event
  src/main/java/com/agiletec/aps/system/common/notify/ApsEvent.java
  src/main/java/com/agiletec/aps/system/services/page/PageManager.java
  src/main/java/com/agiletec/aps/system/services/page/events/PageChangedEvent.java
  src/test/java/com/agiletec/aps/system/common/notify/NotifyManagerTest.java
Labels: prepared
