Repository entando/entando-engine, pull requests merged in 2021-06, with the labels that each got.

#148 ENG-2405 and ENG-2450 Allowing LocalDateTime object as filter
  pom.xml
  src/main/java/com/agiletec/aps/system/common/AbstractSearcherDAO.java
  src/test/java/org/entando/entando/web/analysis/AnalysisControllerTest.java
Labels: approved, size/XS

#149 ENG-2332: Fix issue of applying filter when sorting
  src/main/java/com/agiletec/aps/system/common/AbstractSearcherDAO.java
  src/main/java/com/agiletec/aps/system/common/FieldSearchFilter.java
  src/main/java/org/entando/entando/web/common/model/RestListRequest.java
  src/test/java/org/entando/entando/web/pagemodel/PageModelControllerIntegrationTest.java
Labels: approved, size/S

#153 ENG-2400 Updating entando-core-parent version and bumping version to …
  pom.xml
  src/main/java/org/entando/entando/web/swagger/SwaggerConfig.java
Labels: size/XS

#155 ENG-2400 Updating entando-core-parent to 6.4.1 version
  pom.xml
Labels: size/XS
