Repository entando/entando-engine, pull requests merged in 2021-02, with the labels that each got.

#106 ENG-1816 Adding new user preferences default owner group, default joi…
  src/main/java/org/entando/entando/aps/system/init/model/portdb/UserPreferences.java
  src/main/java/org/entando/entando/aps/system/services/userpreferences/UserPreferences.java
  src/main/java/org/entando/entando/aps/system/services/userpreferences/UserPreferencesDAO.java
  src/main/java/org/entando/entando/aps/system/services/userpreferences/UserPreferencesService.java
  src/main/java/org/entando/entando/web/userpreferences/model/UserPreferencesDto.java
  src/main/java/org/entando/entando/web/userpreferences/model/UserPreferencesRequest.java
  src/test/java/org/entando/entando/web/userpreferences/1_PUT_user_preferences.json
  src/test/java/org/entando/entando/web/userpreferences/2_PUT_user_preferences.json
  src/test/java/org/entando/entando/web/userpreferences/5_PUT_user_preferences.json
  src/test/java/org/entando/entando/web/userpreferences/8_PUT_user_preferences.json
  src/test/java/org/entando/entando/web/userpreferences/UserPreferencesControllerIntegrationTest.java
Labels: approved, size/L

#108 ENG-1836 Adding two more user preferences and removing displayAttributes
  src/main/java/org/entando/entando/aps/system/init/model/portdb/UserPreferences.java
  src/main/java/org/entando/entando/aps/system/services/userpreferences/UserPreferences.java
  src/main/java/org/entando/entando/aps/system/services/userpreferences/UserPreferencesDAO.java
  src/main/java/org/entando/entando/aps/system/services/userpreferences/UserPreferencesService.java
  src/main/java/org/entando/entando/web/userpreferences/model/UserPreferencesDto.java
  src/main/java/org/entando/entando/web/userpreferences/model/UserPreferencesRequest.java
  src/test/java/org/entando/entando/web/userpreferences/1_PUT_user_preferences.json
  src/test/java/org/entando/entando/web/userpreferences/2_PUT_user_preferences.json
  src/test/java/org/entando/entando/web/userpreferences/5_PUT_user_preferences.json
  src/test/java/org/entando/entando/web/userpreferences/8_PUT_user_preferences.json
  src/test/java/org/entando/entando/web/userpreferences/UserPreferencesControllerIntegrationTest.java
Labels: approved, size/L

#109 ENG-1788 add non-null sketch object
  src/main/resources/sql/entandoPort_data_production.sql
Labels: size/XS

#110 ENG-1688 Fixing bug when BE receives an empty array for the new user …
  src/main/java/org/entando/entando/web/userpreferences/model/UserPreferencesDto.java
  src/test/java/org/entando/entando/web/userpreferences/9_PUT_user_preferences.json
  src/test/java/org/entando/entando/web/userpreferences/UserPreferencesControllerIntegrationTest.java
Labels: approved, size/M

#107 ENG-1461 add new icon field to WidgetCatalog table and APIs
  src/main/db/update/scriptPort.sql
  src/main/java/org/entando/entando/aps/system/init/model/portdb/WidgetCatalog.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/IWidgetTypeDAO.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/IWidgetTypeManager.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetService.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetType.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetTypeDAO.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/WidgetTypeManager.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/api/ApiWidgetTypeInterface.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/api/JAXBWidgetType.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/model/WidgetDto.java
  src/main/java/org/entando/entando/aps/system/services/widgettype/model/WidgetDtoBuilder.java
  src/main/java/org/entando/entando/web/widget/WidgetController.java
  src/main/java/org/entando/entando/web/widget/model/WidgetRequest.java
  src/main/resources/sql/entandoPort_data_production.sql
  src/test/java/com/agiletec/aps/system/services/widgettype/TestWidgetType.java
  src/test/java/com/agiletec/aps/system/services/widgettype/TestWidgetTypeDAO.java
  src/test/java/com/agiletec/aps/system/services/widgettype/TestWidgetTypeManager.java
  src/test/java/org/entando/entando/aps/system/services/widgettype/WidgetServiceTest.java
  src/test/java/org/entando/entando/web/widget/WidgetControllerIntegrationTest.java
  src/test/resources/sql/entandoPort_data_test.sql
Labels: approved, size/L

#111 ENG-1813 Implementing search by title
  src/main/java/com/agiletec/aps/system/services/page/IPageManager.java
  src/main/java/com/agiletec/aps/system/services/page/PageManager.java
  src/main/java/org/entando/entando/aps/system/services/page/PageService.java
  src/main/java/org/entando/entando/web/page/model/PageSearchRequest.java
  src/test/java/com/agiletec/aps/system/services/page/TestPageManager.java
  src/test/java/org/entando/entando/web/page/PageControllerIntegrationTest.java
Labels: approved, size/L

#112 ENG-1461 icon name amended
  src/main/resources/sql/entandoPort_data_production.sql
Labels: approved, size/XS

#113 ENG-1892 Adding widget groups user preferences
  src/main/java/org/entando/entando/aps/system/init/model/portdb/UserPreferences.java
  src/main/java/org/entando/entando/aps/system/services/userpreferences/UserPreferences.java
  src/main/java/org/entando/entando/aps/system/services/userpreferences/UserPreferencesDAO.java
  src/main/java/org/entando/entando/aps/system/services/userpreferences/UserPreferencesService.java
  src/main/java/org/entando/entando/web/userpreferences/model/UserPreferencesDto.java
  src/main/java/org/entando/entando/web/userpreferences/model/UserPreferencesRequest.java
  src/test/java/org/entando/entando/web/userpreferences/2_PUT_user_preferences.json
  src/test/java/org/entando/entando/web/userpreferences/9_PUT_user_preferences.json
  src/test/java/org/entando/entando/web/userpreferences/UserPreferencesControllerIntegrationTest.java
Labels: approved, size/L
