Repository entando/entando-engine, pull requests merged in 2021-01, with the labels that each got.

#98 ENG-1665 simplified health check
  src/main/java/org/entando/entando/aps/servlet/security/SecurityWebApplicationInitializer.java
  src/main/java/org/entando/entando/web/health/HealthFilter.java
Labels: approved, size/S

#101 ENG-1626 add a test to check date list attribute with validation rules
  src/test/java/org/entando/entando/web/dataobject/5_PUT_valid_list_date_nested_attribute.json
  src/test/java/org/entando/entando/web/dataobject/DataTypeControllerIntegrationTest.java
Labels: approved, size/L

#96 ENG-1658: allow configuring CSP from environment variables
  src/main/java/com/agiletec/aps/system/SystemConstants.java
  src/main/java/org/entando/entando/aps/servlet/StartupListener.java
  src/main/resources/spring/aps/managers/baseManagersConfig.xml
  src/test/config/conf/systemParams.properties
  src/test/java/com/agiletec/aps/system/services/baseconfig/TestBaseConfigService.java
Labels: approved, size/S

#102 ENG-1658: Fix environment variable names
  src/main/java/com/agiletec/aps/system/SystemConstants.java
  src/main/java/org/entando/entando/aps/servlet/StartupListener.java
Labels: approved, size/XS

#104 ENG-1755 Fixing file separator for windows
  src/main/java/org/entando/entando/aps/system/services/storage/FileBrowserService.java
Labels: approved, size/XS
