Repository entando/entando-engine, pull requests merged in 2021-03, with the labels that each got.

#114 ENG-1088 add email configuration messages
  src/main/resources/rest/messages.properties
Labels: approved, size/S

#115 ENG-1929 Removing camel case from DB columns
  src/main/java/org/entando/entando/aps/system/init/model/portdb/UserPreferences.java
  src/main/java/org/entando/entando/aps/system/services/userpreferences/UserPreferencesDAO.java
Labels: approved, size/M

#116 ENG-1933 Updating editUser permission
  src/main/java/org/entando/entando/web/userprofile/ProfileController.java
  src/main/resources/sql/entandoServ_data_production.sql
  src/test/java/org/entando/entando/web/permission/PermissionControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/userprofile/UserProfileControllerIntegrationTest.java
  src/test/resources/sql/entandoServ_data_test.sql
Labels: approved, size/M

#117 ENG-1918 add new PUT myProfile API
  src/main/java/org/entando/entando/web/userprofile/ProfileController.java
  src/test/java/org/entando/entando/web/userprofile/11_POST_type_valid.json
  src/test/java/org/entando/entando/web/userprofile/11_POST_valid.json
  src/test/java/org/entando/entando/web/userprofile/11_PUT_invalid.json
  src/test/java/org/entando/entando/web/userprofile/11_PUT_valid.json
  src/test/java/org/entando/entando/web/userprofile/UserProfileControllerIntegrationTest.java
Labels: approved, size/L

#118 ENG-1918 add GET myProfile API
  src/main/java/org/entando/entando/web/userprofile/ProfileController.java
  src/test/java/org/entando/entando/web/userprofile/UserProfileControllerIntegrationTest.java
Labels: approved, size/M

#120 ENG-1953 Updating content supervision permission
  src/main/java/org/entando/entando/web/page/PageController.java
  src/main/resources/sql/entandoServ_data_production.sql
  src/test/java/org/entando/entando/web/page/PageControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/permission/PermissionControllerIntegrationTest.java
  src/test/resources/sql/entandoServ_data_test.sql
Labels: approved, size/S

#119 ENG-1918 add new myProfileType API and change mapping for myProfile APIs
  src/main/java/org/entando/entando/web/userprofile/ProfileController.java
  src/main/java/org/entando/entando/web/userprofile/ProfileTypeController.java
  src/test/java/org/entando/entando/web/userprofile/ProfileTypeControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/userprofile/UserProfileControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/utils/OAuth2TestUtils.java
Labels: approved, size/L

#121 ENG-1912 Updating manageResources permission description
  src/main/resources/sql/entandoServ_data_production.sql
  src/test/java/org/entando/entando/web/permission/PermissionControllerIntegrationTest.java
  src/test/resources/sql/entandoServ_data_test.sql
Labels: approved, size/XS

#124 #ENG-2052 Adding profile picture to user profile as an attribute
  src/main/java/com/agiletec/aps/system/SystemConstants.java
  src/main/java/org/entando/entando/aps/system/services/userprofile/attributeRoles.xml
  src/main/resources/sql/entandoPort_data_production.sql
  src/test/java/org/entando/entando/web/userprofile/12_POST_valid.json
  src/test/java/org/entando/entando/web/userprofile/12_PUT_valid.json
  src/test/java/org/entando/entando/web/userprofile/ProfileTypeControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/userprofile/UserProfileControllerIntegrationTest.java
  src/test/resources/sql/entandoPort_data_test.sql
Labels: approved, size/L

#125 #ENG-2047 Adding new reviewer role
  src/main/java/com/agiletec/aps/system/services/role/Permission.java
  src/main/resources/sql/entandoServ_data_production.sql
  src/test/java/org/entando/entando/web/permission/PermissionControllerIntegrationTest.java
  src/test/resources/sql/entandoServ_data_test.sql
Labels: approved, size/S

#126 #ENG-2067 Creating role reviewer and review management permission
  src/main/java/com/agiletec/aps/system/services/role/Permission.java
  src/main/resources/sql/entandoServ_data_production.sql
  src/test/java/org/entando/entando/web/permission/PermissionControllerIntegrationTest.java
  src/test/resources/sql/entandoServ_data_test.sql
Labels: approved, size/S

#128 #ENG-2033 When we GET in pages, we should not include free access pages
  src/main/java/com/agiletec/aps/system/services/authorization/AuthorizationManager.java
  src/main/java/com/agiletec/aps/system/services/authorization/IAuthorizationManager.java
  src/main/java/org/entando/entando/aps/system/services/auth/IAuthorizationService.java
  src/main/java/org/entando/entando/aps/system/services/page/PageAuthorizationService.java
  src/test/java/org/entando/entando/aps/system/services/page/PageAuthorizationServiceIntegrationTest.java
  src/test/java/org/entando/entando/web/page/PageControllerIntegrationTest.java
  src/test/java/org/entando/entando/web/page/PageControllerTest.java
Labels: approved, size/M

#129 #ENG-2113 Adding ECR permission to the OOTB permissions
  src/main/java/com/agiletec/aps/system/services/role/Permission.java
  src/main/resources/sql/entandoServ_data_production.sql
  src/test/java/org/entando/entando/web/permission/PermissionControllerIntegrationTest.java
  src/test/resources/sql/entandoServ_data_test.sql
Labels: approved, size/M
